$c = [System.IO.File]::ReadAllText('Color.csproj')
$c = $c.Replace('Include="extractors\', 'Include="Src\extractors\')
$c = $c.Replace('Include="LogicDocs\', 'Include="Src\LogicDocs\')
$c = $c.Replace('Include="Services\', 'Include="Src\Services\')
$c = $c.Replace('Include="Forms\', 'Include="Presentation\Forms\')
$c = $c.Replace('Include="big_data\', 'Include="Data\big_data\')
$c = $c.Replace('Include="Models\', 'Include="Data\Models\')
$c = $c.Replace('Include="Tolerancias\', 'Include="Data\Tolerancias\')
$c = $c.Replace('Include="tesdata\', 'Include="Data\tesdata\')
[System.IO.File]::WriteAllText('Color.csproj', $c, [System.Text.Encoding]::UTF8)
